### ISSUE TITLE
Regarding Preprocessing

### ISSUE THREAD

**Issue by Abhilashsabhi** [HKUST-DRIVE-AI-LAB/FollowNet#5]
Can you please give the code for preprocessing the data and how you extracted the car following scenarios from the dataset?

**Comment by Xianda-Chen** [comment]
It is difficult to provide a unified code to describe the preprocessing process due to different data sets having different data formats and frameworks. However, our paper provides some pseudo-code for you to refer to the ideas of extracting car-following scenarios. If you have any other questions or need help, please feel free to contact us.  Our email address is ：xchen595@connect.ust.hk

**Comment by Abhilashsabhi** [comment]
Atleast for SPMD dataset, can you provide?

**Comment by Xianda-Chen** [comment]
> Atleast for SPMD dataset, can you provide?

Unfortunately, we cannot provide the code for SPMD dataset at this time as there are still other ongoing works. However, we will consider open-sourcing in the future. Thank you for your understanding.

Below are the tips: The DataFrontTargets file collects front target information such as distance to the front target and relative speed for the front target. The two files were linked by common data fields "Device", "Trip" and "Time".

**Comment by Abhilashsabhi** [comment]
You mentioned two files; one is DataFrrontTargets. What is the other one?
