### ISSUE TITLE
Regarding Data

### ISSUE THREAD

**Issue by Abhilashsabhi** [HKUST-DRIVE-AI-LAB/FollowNet#7]
In the dataset provided, the dimension of highD dataset is (12541, 4, 375). From my understanding, 4 is the number of features, and the third dimension is the data for 15s. but in other datasets, there are only two dimensions(for example SPMD data (16658, 4)) why is that?

**Comment by Xianda-Chen** [comment]
In the HighD dataset, the third dimension represents the data for a duration of 15 seconds. The reason for having a third dimension in the HighD dataset is that the length of each event is **strictly limited to 375** data points.

On the other hand, in the SPMD dataset, there are only two dimensions because the data points do not have a fixed duration.
