### ISSUE TITLE
Dataset dimension error

### ISSUE THREAD

**Issue by ganhaoting** [HKUST-DRIVE-AI-LAB/FollowNet#9]
Out of 5 datasets, except for the HighD dataset, all other four datasets have incorrect dimensions
## 1.HighD
![1711969740031](https://github.com/HKUST-DRIVE-AI-LAB/FollowNet/assets/66521037/5c915eab-5d8b-43c8-ae08-12473a2006a7)
## 2.NGSIM
![1711969779158](https://github.com/HKUST-DRIVE-AI-LAB/FollowNet/assets/66521037/6b146750-424d-405e-bb08-2cce6da05d6d)

## 3.Waymo
![1711969805427](https://github.com/HKUST-DRIVE-AI-LAB/FollowNet/assets/66521037/2c58aec0-12d9-440c-aa7f-d11bc722c5f4)

**Comment by Xianda-Chen** [comment]
Thanks for your question, please refer to the Colab tutorial for more details that can address your concern.

**Comment by Xianda-Chen** [comment]
In the HighD dataset, the third dimension represents the data for a duration of 15 seconds. The reason for having a third dimension in the HighD dataset is that the length of each event is strictly limited to 375 data points.

On the other hand, in the SPMD dataset, there are only two dimensions because the data points do not have a fixed duration.
